Repository VirtusLab/scala-cli, pull requests merged in 2022-10, with the labels that each got.

#1417 Ensure the the `repl` & default sub-commands respect group help options
  modules/cli/src/main/scala/scala/cli/commands/Repl.scala
  modules/integration/src/test/scala/scala/cli/integration/DefaultTests.scala
Labels: bug

#1426 Tweak the release procedure
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_release.md
  .github/release/release-procedure.md
Labels: internal

#1438 Add javacOpt using directive
  modules/build/src/main/scala/scala/build/Build.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/build/src/test/scala/scala/build/tests/DirectiveTests.scala
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/util/JvmUtils.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingJavaOptionsDirectiveHandler.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingJavacOptionsDirectiveHandler.scala
  modules/options/src/main/scala/scala/build/options/JavaOptions.scala
  website/docs/commands/compile.md
  website/docs/commands/run.md
  website/docs/reference/directives.md
  website/docs/reference/scala-command/directives.md
Labels: enhancement

#1441 Debugging cookbook
  website/docs/cookbooks/debugging.md
  website/static/img/debugging_attach_to_process.png
  website/static/img/debugging_configuration_dropdown.png
  website/static/img/debugging_listen_mode_config.png
  website/static/img/debugging_run_doctor_view.png
  website/static/img/debugging_running_debug_configuration.png
  website/static/img/debugging_running_debugger.png
  website/static/img/debugging_setting_breakpoints_intellij.png
  website/static/img/debugging_setting_breakpoints_vs_code.png
Labels: documentation

#1440 Refactor `ScalaCommand` to enforce respecting help options
  modules/cli/src/main/scala/scala/cli/commands/About.scala
  modules/cli/src/main/scala/scala/cli/commands/AddPath.scala
  modules/cli/src/main/scala/scala/cli/commands/BloopExit.scala
  modules/cli/src/main/scala/scala/cli/commands/BloopStart.scala
  modules/cli/src/main/scala/scala/cli/commands/Bsp.scala
  modules/cli/src/main/scala/scala/cli/commands/Clean.scala
  modules/cli/src/main/scala/scala/cli/commands/Compile.scala
  modules/cli/src/main/scala/scala/cli/commands/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/DependencyUpdate.scala
  modules/cli/src/main/scala/scala/cli/commands/Directories.scala
  modules/cli/src/main/scala/scala/cli/commands/Doc.scala
  modules/cli/src/main/scala/scala/cli/commands/Doctor.scala
  modules/cli/src/main/scala/scala/cli/commands/Export.scala
  modules/cli/src/main/scala/scala/cli/commands/Fmt.scala
  modules/cli/src/main/scala/scala/cli/commands/HelpCmd.scala
  modules/cli/src/main/scala/scala/cli/commands/InstallCompletions.scala
  modules/cli/src/main/scala/scala/cli/commands/InstallHome.scala
  modules/cli/src/main/scala/scala/cli/commands/Metabrowse.scala
  modules/cli/src/main/scala/scala/cli/commands/Package.scala
  modules/cli/src/main/scala/scala/cli/commands/Repl.scala
  modules/cli/src/main/scala/scala/cli/commands/Run.scala
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/SetupIde.scala
  modules/cli/src/main/scala/scala/cli/commands/Shebang.scala
  modules/cli/src/main/scala/scala/cli/commands/Test.scala
  modules/cli/src/main/scala/scala/cli/commands/Uninstall.scala
  modules/cli/src/main/scala/scala/cli/commands/UninstallCompletions.scala
  modules/cli/src/main/scala/scala/cli/commands/Update.scala
  modules/cli/src/main/scala/scala/cli/commands/Version.scala
  modules/cli/src/main/scala/scala/cli/commands/bloop/Bloop.scala
  modules/cli/src/main/scala/scala/cli/commands/bloop/BloopOutput.scala
  modules/cli/src/main/scala/scala/cli/commands/config/Config.scala
  modules/cli/src/main/scala/scala/cli/commands/default/DefaultFile.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretCreate.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretList.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpCreate.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpKeyId.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpPull.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpPush.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpSign.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpVerify.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/Publish.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishLocal.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishSetup.scala
  modules/cli/src/test/scala/cli/commands/tests/ReplOptionsTests.scala
  modules/cli/src/test/scala/cli/commands/tests/RunOptionsTests.scala
Labels: bug, UX

#1501 Ensure compiler options relevant to syntax rewriting don't require being passed after `-O`
  modules/cli-options/src/main/scala/scala/cli/commands/ScalacOptions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
Labels: SIP, scalac backwards compatibility

#1503 Improve the docs on using Scala compiler options
  website/docs/commands/compile.md
Labels: documentation, scalac backwards compatibility
