Repository VirtusLab/scala-cli, pull requests merged in 2022-08, with the labels that each got.

#1195 Prevent erroneous using directives from blocking the initial run of BSP
  modules/build/src/main/scala/scala/build/Build.scala
  modules/build/src/main/scala/scala/build/CrossSources.scala
  modules/build/src/main/scala/scala/build/bsp/BspImpl.scala
  modules/build/src/main/scala/scala/build/bsp/BspReloadableOptions.scala
  modules/build/src/main/scala/scala/build/preprocessing/DataPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ExtractedDirectives.scala
  modules/build/src/main/scala/scala/build/preprocessing/JavaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/Preprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScriptPreprocessor.scala
  modules/build/src/test/scala/scala/build/tests/DirectiveParsingTest.scala
  modules/core/src/main/scala/scala/build/errors/BuildException.scala
  modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
  modules/options/src/main/scala/scala/build/Artifacts.scala
  modules/options/src/main/scala/scala/build/options/BuildOptions.scala
Labels: bug

#1213 Define `output` option for `package` command with using directives
  modules/build/src/test/scala/scala/build/tests/PackagingUsingDirectiveTests.scala
  modules/cli/src/main/scala/scala/cli/commands/Package.scala
  modules/cli/src/main/scala/scala/cli/commands/util/PackageOptionsUtil.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingPackagingDirectiveHandler.scala
  modules/options/src/main/scala/scala/build/options/PackageOptions.scala
  website/docs/commands/package.md
  website/docs/reference/directives.md
Labels: enhancement

#1225 NIT Tweak integration tests
  modules/integration/docker/src/test/scala/scala/cli/integration/RunDockerTests.scala
  modules/integration/src/main/scala/scala/cli/integration/TestInputs.scala
  modules/integration/src/test/scala/scala/cli/integration/BloopTests.scala
  modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/CleanTests.scala
  modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/CompileTests212.scala
  modules/integration/src/test/scala/scala/cli/integration/ConfigTests.scala
  modules/integration/src/test/scala/scala/cli/integration/DefaultFileTests.scala
  modules/integration/src/test/scala/scala/cli/integration/DependencyUpdateTests.scala
  modules/integration/src/test/scala/scala/cli/integration/DocTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/DocTestsDefault.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportMillTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportSbtTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportTestProjects.scala
  modules/integration/src/test/scala/scala/cli/integration/FmtTests.scala
  modules/integration/src/test/scala/scala/cli/integration/GitHubTests.scala
  modules/integration/src/test/scala/scala/cli/integration/InstallAndUninstallCompletionsTests.scala
  modules/integration/src/test/scala/scala/cli/integration/InstallHomeTests.scala
  modules/integration/src/test/scala/scala/cli/integration/JmhTests.scala
  modules/integration/src/test/scala/scala/cli/integration/MetaCheck.scala
  modules/integration/src/test/scala/scala/cli/integration/NativePackagerTests.scala
  modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/PgpTests.scala
  modules/integration/src/test/scala/scala/cli/integration/PublishSetupTests.scala
  modules/integration/src/test/scala/scala/cli/integration/PublishTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/PublishTestsDefault.scala
  modules/integration/src/test/scala/scala/cli/integration/ReplTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/ReplTests.scala
  modules/integration/src/test/scala/scala/cli/integration/ReplTests213.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTests212.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestsDefault.scala
  modules/integration/src/test/scala/scala/cli/integration/SharedRunTests.scala
  modules/integration/src/test/scala/scala/cli/integration/SipScalaTests.scala
  modules/integration/src/test/scala/scala/cli/integration/SparkTests212.scala
  modules/integration/src/test/scala/scala/cli/integration/TestBspClient.scala
  modules/integration/src/test/scala/scala/cli/integration/TestNativeImageOnScala3.scala
  modules/integration/src/test/scala/scala/cli/integration/TestScalaVersionArgs.scala
  modules/integration/src/test/scala/scala/cli/integration/TestTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/TestTestsDefault.scala
  modules/integration/src/test/scala/scala/cli/integration/UpdateTests.scala
  modules/integration/src/test/scala/scala/cli/integration/util/BloopUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/util/DockerServer.scala
Labels: internal

#1268 Experimental support for Markdown
  modules/build/src/main/scala/scala/build/CrossSources.scala
  modules/build/src/main/scala/scala/build/Inputs.scala
  modules/build/src/main/scala/scala/build/Sources.scala
  modules/build/src/main/scala/scala/build/internal/markdown/MarkdownCodeBlock.scala
  modules/build/src/main/scala/scala/build/internal/markdown/MarkdownCodeWrapper.scala
  modules/build/src/main/scala/scala/build/internal/markdown/MarkdownOpenFence.scala
  modules/build/src/main/scala/scala/build/preprocessing/MarkdownPreprocessor.scala
  modules/build/src/test/scala/scala/build/tests/PreprocessingTests.scala
  modules/build/src/test/scala/scala/build/tests/markdown/MarkdownCodeWrapperTests.scala
  modules/cli-options/src/main/scala/scala/cli/commands/MarkdownOptions.scala
  modules/cli-options/src/main/scala/scala/cli/commands/SharedOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/Repl.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/TestTestDefinitions.scala
  website/docs/guides/markdown.md
  website/docs/reference/cli-options.md
  website/docs/reference/commands.md
Labels: enhancement

#1286 Fix path to sourceMappingURL
  modules/cli/src/main/scala/scala/cli/commands/Package.scala
  modules/cli/src/main/scala/scala/cli/internal/ScalaJsLinker.scala
  modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala
Labels: bug
