Repository VirtusLab/scala-cli, pull requests merged in 2022-11, with the labels that each got.

#1513 Improve the basics doc
  website/docs/commands/basics.md
Labels: documentation

#1521 Fix a typo in the `--server` option reference doc
  modules/cli-options/src/main/scala/scala/cli/commands/SharedCompilationServerOptions.scala
  website/docs/reference/cli-options.md
  website/docs/reference/scala-command/cli-options.md
Labels: bug, documentation

#1504 Tweak documentation verification tests
  README.md
  modules/docs-tests/src/test/scala/sclicheck/DocTests.scala
  website/docs/guides/configuration.md
  website/docs/guides/dependencies.md
  website/docs/guides/scripts.md
Labels: documentation, internal

#1525 Fix the `nativeEmbedResources` using directive
  modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingScalaNativeOptionsDirectiveHandler.scala
Labels: bug

#1518 Return exit code 1 when build fails for test
  modules/build/src/main/scala/scala/build/Builds.scala
  modules/cli/src/main/scala/scala/cli/commands/Test.scala
  modules/integration/src/test/scala/scala/cli/integration/TestTestDefinitions.scala
Labels: bug

#1540 Dump docusaurus to 2.20 and other docs deps
  website/package.json
  website/yarn.lock
Labels: documentation, internal

#1529 Decompose RunTestDefinitions
  modules/integration/src/test/scala/scala/cli/integration/HelpTests.scala
  modules/integration/src/test/scala/scala/cli/integration/MarkdownTests.scala
  modules/integration/src/test/scala/scala/cli/integration/RunGistTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunScalaJsTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunScalaNativeTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunScalaPyTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunScalacCompatTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunScriptTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunSnippetTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunZipTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/VersionTests.scala
Labels: internal

#1507 Merge documentation of installing scala-cli on MacOs and MacOs/M1
  website/docs/_advanced_install.mdx
Labels: documentation

#1549 docs: Update the recommened installation options for SiP Scala
  website/docs/reference/scala-command/index.md
Labels: documentation

#1560 Change project settings filename
  modules/build/src/main/scala/scala/build/CrossSources.scala
  modules/build/src/main/scala/scala/build/Inputs.scala
  modules/build/src/test/scala/scala/build/tests/InputsTests.scala
  website/docs/reference/root-dir.md
Labels: enhancement

#1561 Fix completions when install by cs - strip suffix .aux
  modules/cli/src/main/scala/scala/cli/commands/installcompletions/InstallCompletions.scala
Labels: bug

#1563 Add option to customize Mill exported project name
  modules/cli-options/src/main/scala/scala/cli/commands/ExportOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/export/Export.scala
  modules/cli/src/main/scala/scala/cli/exportCmd/Mill.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportMillTestDefinitions.scala
  website/docs/reference/cli-options.md
Labels: enhancement

#1562 Generate scalacOptions in Mill project
  modules/cli/src/main/scala/scala/cli/exportCmd/Mill.scala
  modules/cli/src/main/scala/scala/cli/exportCmd/MillProject.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportMillTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportTestProjects.scala
Labels: enhancement

#1565 Decompose & refactor `Inputs`
  modules/build/src/main/scala/scala/build/Build.scala
  modules/build/src/main/scala/scala/build/CrossSources.scala
  modules/build/src/main/scala/scala/build/Sources.scala
  modules/build/src/main/scala/scala/build/bsp/BloopSession.scala
  modules/build/src/main/scala/scala/build/bsp/Bsp.scala
  modules/build/src/main/scala/scala/build/bsp/BspImpl.scala
  modules/build/src/main/scala/scala/build/bsp/BuildServerProxy.scala
  modules/build/src/main/scala/scala/build/bsp/HasGeneratedSources.scala
  modules/build/src/main/scala/scala/build/bsp/HasGeneratedSourcesImpl.scala
  modules/build/src/main/scala/scala/build/input/Element.scala
  modules/build/src/main/scala/scala/build/input/ElementsUtils.scala
  modules/build/src/main/scala/scala/build/input/Inputs.scala
  modules/build/src/main/scala/scala/build/input/WorkspaceOrigin.scala
  modules/build/src/main/scala/scala/build/internal/MainClass.scala
  modules/build/src/main/scala/scala/build/internal/resource/NativeResourceMapper.scala
  modules/build/src/main/scala/scala/build/preprocessing/DataPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/JavaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/MarkdownPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/Preprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScriptPreprocessor.scala
  modules/build/src/test/scala/scala/build/tests/BuildProjectTests.scala
  modules/build/src/test/scala/scala/build/tests/InputsTests.scala
  modules/build/src/test/scala/scala/build/tests/PreprocessingTests.scala
  modules/build/src/test/scala/scala/build/tests/TestInputs.scala
  modules/cli/src/main/scala/scala/cli/commands/bsp/Bsp.scala
  modules/cli/src/main/scala/scala/cli/commands/clean/Clean.scala
  modules/cli/src/main/scala/scala/cli/commands/export/Export.scala
  modules/cli/src/main/scala/scala/cli/commands/fmt/Fmt.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/Publish.scala
  modules/cli/src/main/scala/scala/cli/commands/repl/Repl.scala
  modules/cli/src/main/scala/scala/cli/commands/run/Run.scala
  modules/cli/src/main/scala/scala/cli/commands/setupide/SetupIde.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/cli/src/main/scala/scala/cli/errors/FoundVirtualInputsError.scala
  modules/cli/src/main/scala/scala/cli/internal/CachedBinary.scala
Labels: internal

#1581 Add support for running `.md` files inside of zipped archives
  modules/build/src/main/scala/scala/build/input/Element.scala
  modules/build/src/main/scala/scala/build/input/Inputs.scala
  modules/build/src/main/scala/scala/build/internal/MainClass.scala
  modules/build/src/main/scala/scala/build/preprocessing/MarkdownPreprocessor.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/RunZipTestDefinitions.scala
Labels: markdown

#1582 Support running piped Markdown sources
  modules/build/src/main/scala/scala/build/input/Inputs.scala
  modules/integration/src/test/scala/scala/cli/integration/RunPipedSourcesTestDefinitions.scala
Labels: markdown

#1583 Add support for passing Markdown code as snippets
  modules/build/src/main/scala/scala/build/input/Inputs.scala
  modules/cli-options/src/main/scala/scala/cli/commands/SnippetOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/default/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishSetup.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/DefaultTests.scala
  modules/integration/src/test/scala/scala/cli/integration/RunSnippetTestDefinitions.scala
  website/docs/guides/snippets.md
  website/docs/reference/cli-options.md
Labels: enhancement, markdown

#1586 Bump Ammonite to 2.5.5-17-df243e14 & Scala to 3.2.1
  project/deps.sc
  website/docs/reference/cli-options.md
  website/docs/reference/scala-command/cli-options.md
  website/docs/reference/scala-versions.md
Labels: dependencies

#1598 Fix `using` directives for Markdown inputs
  modules/build/src/main/scala/scala/build/internal/markdown/MarkdownCodeBlock.scala
  modules/build/src/main/scala/scala/build/internal/markdown/MarkdownCodeWrapper.scala
  modules/build/src/main/scala/scala/build/internal/markdown/MarkdownOpenFence.scala
  modules/build/src/main/scala/scala/build/preprocessing/ExtractedDirectives.scala
  modules/build/src/main/scala/scala/build/preprocessing/MarkdownCodeBlockProcessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/MarkdownPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/PreprocessedMarkdown.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/build/src/test/scala/scala/build/tests/markdown/MarkdownCodeBlockTests.scala
  modules/build/src/test/scala/scala/build/tests/markdown/MarkdownCodeWrapperTests.scala
  modules/build/src/test/scala/scala/build/tests/markdown/MarkdownTestUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/MarkdownTests.scala
Labels: bug, markdown

#1617 Reduce ignore tags in the docs snippets
  website/docs/commands/basics.md
  website/docs/commands/compile.md
  website/docs/commands/package.md
  website/docs/commands/repl.md
  website/docs/commands/run.md
  website/docs/commands/test.md
  website/docs/cookbooks/instant-startup-scala-scripts.md
  website/docs/cookbooks/intellij-multi-bsp.md
  website/docs/guides/configuration.md
  website/docs/guides/dependencies.md
  website/docs/guides/scala-js.md
  website/docs/guides/scripts.md
  website/docs/guides/snippets.md
Labels: documentation

#1618 Add release notes for v0.1.18
  website/docs/release_notes.md
Labels: internal
