Repository VirtusLab/scala-cli, pull requests merged in 2022-06, with the labels that each got.

#1040 Add more interactive options
  modules/build/src/main/scala/scala/build/Build.scala
  modules/build/src/main/scala/scala/build/interactive/Interactive.scala
  modules/cli-options/src/main/scala/scala/cli/commands/SharedOptions.scala
  modules/cli-options/src/main/scala/scala/cli/commands/VerbosityOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/Doc.scala
  modules/cli/src/main/scala/scala/cli/commands/Fmt.scala
  modules/cli/src/main/scala/scala/cli/commands/InstallCompletions.scala
  modules/cli/src/main/scala/scala/cli/commands/Package.scala
  modules/cli/src/main/scala/scala/cli/commands/Update.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/cli/src/main/scala/scala/cli/commands/util/VerbosityOptionsUtil.scala
  modules/options/src/main/scala/scala/build/interactive/Interactive.scala
  modules/options/src/main/scala/scala/build/interactive/InteractiveFileOps.scala
  modules/options/src/main/scala/scala/build/options/BuildOptions.scala
  website/docs/reference/cli-options.md
Labels: enhancement

#1096 Force retry to download scala-version when not found in cache
  modules/options/src/main/scala/scala/build/options/BuildOptions.scala
  modules/options/src/main/scala/scala/build/options/ScalaVersionUtil.scala
Labels: bug

#1080 Convert relative path to absolute for coverage options
  modules/build/src/main/scala/scala/build/Project.scala
  modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala
Labels: bug

#1108 Update scala 2.12 to 2.12.16 in docs
  modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingScalaVersionDirectiveHandler.scala
  website/docs/commands/compile.md
  website/docs/cookbooks/scala-versions.md
  website/docs/reference/directives.md
Labels: documentation, update

#1118 Add handling of `--list-main-classes` for `publish` & `package` commands
  modules/cli/src/main/scala/scala/cli/commands/Package.scala
  modules/cli/src/main/scala/scala/cli/commands/Run.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/Publish.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishLocal.scala
  modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/PublishTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
Labels: enhancement
