Repository VirtusLab/scala-cli, pull requests merged in 2022-12, with the labels that each got.

#1639 Fix using directives not working with the shebang line in `.scala` files
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/build/src/test/scala/scala/build/tests/ScalaPreprocessorTests.scala
Labels: bug

#1647 Ignore `shebang` headers in `scala` code blocks in Markdown inputs
  modules/build/src/main/scala/scala/build/internal/markdown/MarkdownOpenFence.scala
  modules/build/src/test/scala/scala/build/tests/markdown/MarkdownCodeBlockTests.scala
  website/docs/guides/markdown.md
Labels: markdown

#1653 Update os-lib to 0.9.0
  project/deps.sc
Labels: dependencies

#1661 fix if else in mill.bat
  mill.bat
Labels: bug, Warsaw Scala Spree

#1681 Fix BSP `workspace/reload` to always pick up dependencies from `using` directives
  modules/build/src/main/scala/scala/build/bsp/BloopSession.scala
  modules/build/src/main/scala/scala/build/bsp/BspImpl.scala
  modules/build/src/main/scala/scala/build/bsp/BuildServerForwardStubs.scala
  modules/build/src/main/scala/scala/build/bsp/BuildServerProxy.scala
  modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
Labels: bug, IDE

#1684 Improve IDE support docs
  website/docs/cookbooks/intellij-multi-bsp.md
  website/docs/cookbooks/intellij-sbt-with-bsp.md
  website/docs/cookbooks/intellij.md
  website/docs/cookbooks/vscode.md
  website/docs/guides/ide.md
Labels: documentation, IDE

#1696 Fix - Skip checking file order
  website/docs/getting_started.md
Labels: internal

#1697 Fix the order of help command groups for the default help
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/ScalaCliHelp.scala
  modules/integration/src/test/scala/scala/cli/integration/HelpTests.scala
Labels: bug, SIP

#1695 Adjust SIP help output & ensure `ScalaSipTests` are run on Windows
  modules/cli/src/main/scala/scala/cli/ScalaCliCommands.scala
  modules/integration/src/test/scala/scala/cli/integration/SipScalaTests.scala
Labels: SIP

#1679 Add warnings for `-save` & `-nosave` legacy `scala` runner options instead of failing
  modules/cli/src/main/scala/scala/cli/commands/default/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/default/DefaultOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/default/LegacyScalaOptions.scala
  modules/integration/src/test/scala/scala/cli/integration/DefaultTests.scala
Labels: SIP

#1718 Add test-only cookbook
  website/docs/cookbooks/test-only.md
Labels: documentation
