Repository VirtusLab/scala-cli, pull requests merged in 2022-07, with the labels that each got.

#1149 Add cookbooks for working with Scala CLI in IDEA IntelliJ
  website/docs/cookbooks/intellij-multi-bsp.md
  website/docs/cookbooks/intellij-sbt-with-bsp.md
  website/docs/cookbooks/intellij.md
  website/docs/cookbooks/vscode.md
  website/static/img/intellij_bsp_build_scripts_found.png
  website/static/img/intellij_bsp_external_model.png
  website/static/img/intellij_bsp_icon.png
  website/static/img/intellij_flat_sources_layout.png
  website/static/img/intellij_import_bsp_module.png
  website/static/img/intellij_imported_project_layout.png
  website/static/img/intellij_module_settings.png
  website/static/img/intellij_module_settings_import_module.png
  website/static/img/intellij_multi_bsp_setup.png
  website/static/img/intellij_open_dir.png
  website/static/img/intellij_project_from_existing_sources.png
  website/static/img/intellij_project_layout_with_extra_dir.png
  website/static/img/intellij_refresh_bsp.png
  website/static/img/intellij_run_code_with_bsp.png
  website/static/img/intellij_sbt_alongside_bsp.png
  website/static/img/intellij_sbt_module_settings.png
Labels: documentation

#1179 Add docs how to install scala-cli via choco
  website/docs/_advanced_install.mdx
Labels: documentation

#1182 Add support for running multiple snippets of the same kind
  modules/build/src/main/scala/scala/build/Build.scala
  modules/build/src/main/scala/scala/build/Inputs.scala
  modules/build/src/main/scala/scala/build/preprocessing/JavaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/cli-options/src/main/scala/scala/cli/commands/SnippetOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  website/docs/guides/snippets.md
Labels: enhancement

#1197 Update jsoniter-scala-core_2.13 to 2.13.37
  project/deps.sc
Labels: update

#1196 Put the release notes doc on the website
  .github/ISSUE_TEMPLATE/new_release.md
  .github/release/release-procedure.md
  .github/release/release_notes.md
  website/docs/release_notes.md
Labels: documentation

#1192 Generate scalafmt conf file on fmt command
  modules/cli-options/src/main/scala/scala/cli/commands/FmtOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/Fmt.scala
  modules/cli/src/main/scala/scala/cli/commands/util/FmtUtil.scala
  modules/cli/src/test/scala/cli/tests/ScalafmtTest.scala
  modules/integration/src/test/scala/scala/cli/integration/FmtTests.scala
  website/docs/commands/fmt.md
  website/docs/reference/cli-options.md
Labels: enhancement

#1201 Add install and uninstall completions documentation
  website/docs/_advanced_install.mdx
  website/docs/commands/completions.md
Labels: documentation
