Repository VirtusLab/scala-cli, pull requests merged in 2022-09, with the labels that each got.

#1313 Fix backwards compat for `-e` and `--scalac-help`
  modules/cli-options/src/main/scala/scala/cli/commands/SharedOptions.scala
  modules/cli-options/src/main/scala/scala/cli/commands/SnippetOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/Repl.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/DefaultTests.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  website/docs/reference/cli-options.md
Labels: SIP

#1314 Update scala3 to 3.2.0
  build.sc
  modules/cli-options/src/main/scala/scala/cli/commands/publish/MaybeConfigPasswordOption.scala
  modules/cli-options/src/main/scala/scala/cli/commands/publish/PublishParamsOptions.scala
  modules/cli-options/src/main/scala/scala/cli/util/ArgParsers.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/Publish.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/checks/PgpSecretKeyCheck.scala
  modules/cli/src/main/scala/scala/cli/commands/util/PublishUtils.scala
  modules/cli/src/main/scala/scala/cli/util/ConfigPasswordOptionHelpers.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/UsingPublishContextualDirectiveHandler.scala
  modules/options/src/main/scala/scala/build/actionable/ActionablePreprocessor.scala
  modules/options/src/main/scala/scala/build/options/PublishContextualOptions.scala
  modules/options/src/main/scala/scala/build/options/publish/ConfigPasswordOption.scala
  modules/tasty-lib/src/main/scala/scala/build/tastylib/TastyVersions.scala
  project/deps.sc
  website/docs/reference/scala-versions.md
Labels: dependencies

#1323 Improve the error message for when a build's main class is ambiguous
  modules/build/src/main/scala/scala/build/Build.scala
  modules/cli/src/main/scala/scala/cli/commands/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/Package.scala
  modules/cli/src/main/scala/scala/cli/commands/Run.scala
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/Publish.scala
  modules/cli/src/main/scala/scala/cli/commands/util/BuildCommandHelpers.scala
  modules/core/src/main/scala/scala/build/errors/SeveralMainClassesFoundError.scala
  modules/integration/src/test/scala/scala/cli/integration/DefaultTests.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/TestUtil.scala
Labels: enhancement

#1327 Improve the error message for unsupported Scala version with Ammonite
  modules/cli/src/main/scala/scala/cli/commands/Repl.scala
  modules/core/src/main/scala/scala/build/errors/CantDownloadAmmoniteError.scala
  modules/core/src/main/scala/scala/build/errors/FetchingDependenciesError.scala
Labels: enhancement, UX

#1340 Make `-d` and `-classpath` options backwards compatible with the `scala` command
  modules/cli-options/src/main/scala/scala/cli/commands/CompileOptions.scala
  modules/cli-options/src/main/scala/scala/cli/commands/ScalacOptions.scala
  modules/cli-options/src/main/scala/scala/cli/commands/SharedDependencyOptions.scala
  modules/cli-options/src/main/scala/scala/cli/commands/SharedOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/Compile.scala
  modules/cli/src/main/scala/scala/cli/commands/Package.scala
  modules/cli/src/main/scala/scala/cli/commands/Run.scala
  modules/cli/src/main/scala/scala/cli/commands/util/BuildCommandHelpers.scala
  modules/cli/src/main/scala/scala/cli/commands/util/ScalacOptionsUtil.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/TestTestsDefault.scala
  modules/options/src/main/scala/scala/build/options/ShadowingSeq.scala
  website/docs/commands/compile.md
  website/docs/reference/cli-options.md
  website/docs/reference/scala-command/cli-options.md
Labels: SIP

#1369 Make inputs optional when `-classpath` and `--main-class` are passed
  modules/build/src/main/scala/scala/build/Build.scala
  modules/build/src/main/scala/scala/build/Inputs.scala
  modules/build/src/main/scala/scala/build/internal/MainClass.scala
  modules/build/src/test/scala/scala/build/tests/TestInputs.scala
  modules/cli/src/main/scala/scala/cli/commands/Clean.scala
  modules/cli/src/main/scala/scala/cli/commands/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/DefaultTests.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
Labels: SIP

#1377 Fix calculation of Scala version and turn off the `-release` flag for 2.12.x < 2.12.5
  modules/build/src/main/scala/scala/build/Build.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  modules/options/src/main/scala/scala/build/options/ScalaVersionUtil.scala
Labels: bug

#1384 NIT ScalaVersionUtil refactor
  modules/build/src/main/scala/scala/build/Build.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/cli/src/main/scala/scala/cli/launcher/LauncherCli.scala
  modules/options/src/main/scala/scala/build/actionable/ActionableDependencyHandler.scala
  modules/options/src/main/scala/scala/build/options/ScalaVersionUtil.scala
Labels: internal

#1380 Fix finding main classes in external jars
  modules/build/src/main/scala/scala/build/internal/MainClass.scala
  modules/cli-options/src/main/scala/scala/cli/commands/SharedOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/util/SharedOptionsUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  website/docs/reference/cli-options.md
  website/docs/reference/scala-command/cli-options.md
Labels: bug, SIP

#1378 Add --debug option for integration tests
  README.md
  build.sc
  modules/integration/src/test/scala/scala/cli/integration/TestUtil.scala
Labels: DX

#1402 Revert scalafmt fix
  gifs/Dockerfile
  gifs/scenarios/defaults.sh
  website/docs/cookbooks/gh-action.md
  website/static/img/dark/defaults.svg
  website/static/img/dark/gifs/defaults.gif
  website/static/img/defaults.svg
  website/static/img/gifs/defaults.gif
Labels: internal

#1405 Bump respective Scala versions to `2.12.17` & `2.13.9` and Ammonite to `2.5.4-33-0af04a5b`
  modules/cli/src/main/scala/scala/cli/commands/Repl.scala
  modules/integration/src/test/scala/scala/cli/integration/ReplTestDefinitions.scala
  project/deps.sc
  website/docs/reference/scala-versions.md
Labels: dependencies
