Repository VirtusLab/scala-cli, pull requests merged in 2023-01, with the labels that each got.

#1737 Remove irrelevant options from `version` help message
  modules/cli/src/main/scala/scala/cli/commands/shared/VerbosityOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/version/Version.scala
  modules/cli/src/main/scala/scala/cli/commands/version/VersionOptions.scala
  modules/cli/src/test/scala/cli/tests/HelpCheck.scala
  website/docs/reference/commands.md
  website/docs/reference/scala-command/commands.md
  website/docs/reference/scala-command/runner-specification.md
Labels: SIP

#1725 Include launcher options in the help for the default and `help` sub-commands
  modules/cli/src/main/scala/scala/cli/ScalaCliCommands.scala
  modules/cli/src/main/scala/scala/cli/commands/HelpCmd.scala
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommandWithCustomHelp.scala
  modules/cli/src/main/scala/scala/cli/commands/default/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/ScalaCliHelp.scala
  modules/cli/src/main/scala/scala/cli/commands/util/HelpUtils.scala
  modules/cli/src/main/scala/scala/cli/launcher/LauncherOptions.scala
  modules/integration/src/test/scala/scala/cli/integration/HelpTests.scala
  modules/integration/src/test/scala/scala/cli/integration/SipScalaTests.scala
Labels: SIP

#1736 Remove suffix `.aux` from progName when installed by cs
  modules/cli/src/main/scala/scala/cli/ScalaCli.scala
  modules/cli/src/main/scala/scala/cli/commands/installcompletions/InstallCompletions.scala
  modules/integration/src/test/scala/scala/cli/integration/SipScalaTests.scala
Labels: SIP

#1739 Add support for passing java properties without --java-prop
  modules/cli/src/main/scala/scala/cli/commands/shared/JavaPropOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/SharedJavaOptions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  website/docs/commands/run.md
  website/docs/reference/cli-options.md
  website/docs/reference/commands.md
  website/docs/reference/scala-command/cli-options.md
  website/docs/reference/scala-command/commands.md
  website/docs/reference/scala-command/runner-specification.md
  website/docs/under-the-hood.md
Labels: SIP

#1746 Update core_2.13 to 3.8.6
  project/deps.sc
Labels: dependencies

#1744 Cleanup `version`, `about` & `doctor` sub-commands
  modules/cli/src/main/scala/scala/cli/ScalaCliCommands.scala
  modules/cli/src/main/scala/scala/cli/commands/about/About.scala
  modules/cli/src/main/scala/scala/cli/commands/about/AboutOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/default/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/doctor/Doctor.scala
  modules/cli/src/main/scala/scala/cli/commands/doctor/DoctorOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/version/Version.scala
  modules/cli/src/main/scala/scala/cli/commands/version/VersionOptions.scala
  website/docs/_advanced_install.mdx
  website/docs/commands/basics.md
  website/docs/commands/version.md
  website/docs/reference/cli-options.md
  website/docs/reference/commands.md
  website/docs/reference/scala-command/cli-options.md
  website/docs/reference/scala-command/commands.md
  website/docs/reference/scala-command/runner-specification.md
Labels: SIP

#1740 Explain the differences in using shebang vs scala-cli directly in script
  modules/docs-tests/src/main/scala/sclicheck/sclicheck.scala
  website/docs/commands/shebang.md
  website/docs/guides/shebang.md
Labels: SIP

#1758 Update core_2.13 to 3.8.7
  project/deps.sc
Labels: dependencies

#1760 Don't fail in case of connection errors in the version sub-command
  modules/cli/src/main/scala/scala/cli/commands/update/Update.scala
  modules/cli/src/main/scala/scala/cli/commands/version/Version.scala
  modules/core/src/main/scala/scala/build/errors/CheckScalaCliVersionError.scala
  modules/integration/src/test/scala/scala/cli/integration/SipScalaTests.scala
  modules/integration/src/test/scala/scala/cli/integration/VersionTests.scala
Labels: internal

#1769 Update ammonite to 2.5.6
  project/deps.sc
  website/docs/reference/cli-options.md
Labels: dependencies

#1771 Set workspace dir to `os.tmp.dir` for virtual sources
  modules/build/src/main/scala/scala/build/input/Inputs.scala
  modules/build/src/main/scala/scala/build/input/WorkspaceOrigin.scala
  modules/integration/src/test/scala/scala/cli/integration/RunSnippetTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
Labels: SIP

#1774 Add support for deprecated Scala `2.13.x`-specific `scala` runner options
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommandWithCustomHelp.scala
  modules/cli/src/main/scala/scala/cli/commands/default/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/default/LegacyScalaOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/VerbosityOptions.scala
  modules/integration/src/test/scala/scala/cli/integration/DefaultTests.scala
  modules/integration/src/test/scala/scala/cli/integration/HelpTests.scala
  modules/integration/src/test/scala/scala/cli/integration/LegacyScalaRunnerTestDefinitions.scala
  website/docs/reference/cli-options.md
  website/docs/reference/scala-command/cli-options.md
  website/docs/reference/scala-command/runner-specification.md
Labels: SIP

#1780 Add support for the `-with-compiler` runner option
  modules/cli/src/main/scala/scala/cli/commands/shared/SharedOptions.scala
  modules/cli/src/main/scala/scala/cli/exportCmd/Mill.scala
  modules/cli/src/main/scala/scala/cli/exportCmd/Sbt.scala
  modules/integration/src/test/scala/scala/cli/integration/CompileTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunScalacCompatTestDefinitions.scala
  modules/options/src/main/scala/scala/build/options/BuildOptions.scala
  modules/options/src/main/scala/scala/build/options/ScalaOptions.scala
  website/docs/reference/cli-options.md
  website/docs/reference/scala-command/cli-options.md
  website/docs/reference/scala-command/runner-specification.md
Labels: SIP

#1782 Add release notes for `v0.1.20`
  website/docs/release_notes.md
Labels: internal

#1798 Update docker example command
  website/docs/commands/run.md
Labels: documentation

#1799 Ignore Bloop server early exit if it signals an already running server
  modules/bloop-rifle/src/main/scala/scala/build/blooprifle/internal/Operations.scala
  project/deps.sc
Labels: bug

#1801 Add a warning for the `-run` option of the legacy `scala` runner, instead of failing
  modules/cli/src/main/scala/scala/cli/commands/default/LegacyScalaOptions.scala
  modules/integration/src/test/scala/scala/cli/integration/LegacyScalaRunnerTestDefinitions.scala
Labels: SIP

#1804 Add warnings for the deprecated `-Yscriptrunner` legacy `scala` runner option instead of passing it to `scalac`
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/default/LegacyScalaOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/ScalacOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/SharedOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/util/ScalacOptionsUtil.scala
  modules/integration/src/test/scala/scala/cli/integration/LegacyScalaRunnerTestDefinitions.scala
  modules/options/src/main/scala/scala/build/options/ShadowingSeq.scala
Labels: SIP

#1812 Filter out `restricted` & `experimental` options from `SIP` mode help
  modules/cli/src/main/scala/scala/cli/commands/RestrictedCommandsParser.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/ScalaCliHelp.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/SharedPythonOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/SnippetOptions.scala
  modules/cli/src/main/scala/scala/cli/util/ArgHelpers.scala
  modules/generate-reference-doc/src/main/scala/scala/cli/doc/GenerateReferenceDoc.scala
  modules/integration/src/test/scala/scala/cli/integration/SipScalaTests.scala
  project/deps.sc
  website/docs/reference/cli-options.md
  website/docs/reference/scala-command/cli-options.md
  website/docs/reference/scala-command/runner-specification.md
Labels: SIP
