Repository VirtusLab/scala-cli, pull requests merged in 2023-02, with the labels that each got.

#1819 Tweak `--watch`/`--restart` disambiguation in the help messages & docs
  modules/cli/src/main/scala/scala/cli/commands/shared/SharedWatchOptions.scala
  website/docs/commands/run.md
  website/docs/reference/cli-options.md
  website/docs/reference/scala-command/cli-options.md
  website/docs/reference/scala-command/runner-specification.md
Labels: SIP

#1814 Prevent NPE from being thrown by the `export` sub-command if `testFramework` isn't defined
  modules/integration/src/test/scala/scala/cli/integration/ExportCommonTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportMillTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportMillTests212.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportMillTests213.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportSbtTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportSbtTests212.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportSbtTests213.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportTestProjects.scala
  modules/test-runner/src/main/scala/scala/build/testrunner/AsmTestRunner.scala
Labels: bug

#1853 Switch `scala-cli-signing` to `org.virtuslab` and bump to `0.1.15`
  DEV.md
  project/deps.sc
Labels: dependencies

#1852 Add more detail for sub-commands' help messages
  modules/cli/src/main/scala/scala/cli/commands/addpath/AddPathOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/bloop/BloopExitOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/bloop/BloopOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/bloop/BloopOutputOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/bloop/BloopStartOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/bsp/BspOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/clean/CleanOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/compile/CompileOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/config/ConfigOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/default/DefaultFileOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/default/LegacyScalaOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/dependencyupdate/DependencyUpdateOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/directories/DirectoriesOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/doc/DocOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/export/ExportOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/export0/Export.scala
  modules/cli/src/main/scala/scala/cli/commands/export0/ExportOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/fmt/FmtOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/github/ListSecretsOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretCreateOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretList.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretListOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SharedSecretOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/installcompletions/InstallCompletionsOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/installhome/InstallHomeOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/package0/PackageOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishLocalOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishSetupOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/repl/ReplOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/run/RunOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/setupide/SetupIdeOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/HelpMessages.scala
  modules/cli/src/main/scala/scala/cli/commands/shebang/ShebangOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/test/TestOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/uninstall/UninstallOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/uninstallcompletions/UninstallCompletionsOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/update/UpdateOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/version/VersionOptions.scala
  website/docs/reference/cli-options.md
  website/docs/reference/commands.md
  website/docs/reference/scala-command/cli-options.md
  website/docs/reference/scala-command/commands.md
  website/docs/reference/scala-command/runner-specification.md
Labels: documentation, SIP, help

#1862 Warn in sip mode when using restricted command
  modules/cli/src/main/scala/scala/cli/ScalaCliCommands.scala
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretCreate.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretList.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/HelpMessages.scala
  modules/integration/src/test/scala/scala/cli/integration/SipScalaTests.scala
Labels: SIP

#1866 Run generate reference doc as non sip
  build.sc
  modules/cli/src/main/scala/scala/cli/ScalaCli.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretCreateOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/uninstall/Uninstall.scala
Labels: SIP

#1871 Trim passwords obtained as command result
  modules/config/src/main/scala/scala/cli/config/PasswordOption.scala
Labels: bug

#1874 Ensure no console-syntax in reference docs and no `md` fenced blocks in `--help`
  modules/build/src/main/scala/scala/build/ConsoleBloopBuildClient.scala
  modules/build/src/main/scala/scala/build/internal/util/ConsoleUtils.scala
  modules/cli/src/main/scala/scala/cli/commands/WatchUtil.scala
  modules/cli/src/main/scala/scala/cli/commands/config/ConfigOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretCreateOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/run/Run.scala
  modules/cli/src/main/scala/scala/cli/commands/run/RunOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/setupide/SetupIdeOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/HelpMessages.scala
  modules/cli/src/main/scala/scala/cli/commands/shebang/ShebangOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/test/Test.scala
  modules/generate-reference-doc/src/main/scala/scala/cli/doc/GenerateReferenceDoc.scala
  modules/generate-reference-doc/src/main/scala/scala/cli/doc/ReferenceDocUtils.scala
  website/docs/reference/commands.md
  website/docs/reference/scala-command/commands.md
  website/docs/reference/scala-command/runner-specification.md
Labels: documentation, help

#1886 Tweak error messages for running scripts without file extensions
  modules/build/src/main/scala/scala/build/input/Inputs.scala
  modules/integration/src/test/scala/scala/cli/integration/RunScriptTestDefinitions.scala
  website/docs/guides/shebang.md
Labels: UX
