Repository VirtusLab/scala-cli, pull requests merged in 2023-04, with the labels that each got.

#1974 Add release notes for `v1.0.0-RC1`
  website/docs/release_notes.md
Labels: documentation, internal

#2002 Fix snapshot versions calculation when the current version ends with `-RC.`
  project/publish.sc
Labels: bug

#2004 Fix completions
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/GlobalOptions.scala
  modules/integration/src/test/scala/scala/cli/integration/CompleteTests.scala
Labels: bug

#2038 Fix - package js without main method
  modules/cli/src/main/scala/scala/cli/commands/package0/Package.scala
  modules/integration/src/test/scala/scala/cli/integration/PackageTestDefinitions.scala
Labels: bug

#2014 Improve error messages for malformed `config` values
  modules/config/src/main/scala/scala/cli/config/CredentialsValue.scala
  modules/config/src/main/scala/scala/cli/config/ErrorMessages.scala
  modules/config/src/main/scala/scala/cli/config/Key.scala
  modules/config/src/main/scala/scala/cli/config/Keys.scala
  modules/config/src/main/scala/scala/cli/config/PasswordOption.scala
  modules/config/src/main/scala/scala/cli/config/PublishCredentials.scala
  modules/config/src/main/scala/scala/cli/config/RepositoryCredentials.scala
  modules/integration/src/test/scala/scala/cli/integration/ConfigTests.scala
Labels: UX

#2046 Support declaring some test directives from the main scope
  modules/build/src/main/scala/scala/build/CrossSources.scala
  modules/build/src/main/scala/scala/build/preprocessing/DataPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/JarPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/JavaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/MarkdownPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/PreprocessedSource.scala
  modules/build/src/main/scala/scala/build/preprocessing/PreprocessingUtil.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScriptPreprocessor.scala
  modules/build/src/test/scala/scala/build/tests/DirectiveTests.scala
  modules/build/src/test/scala/scala/build/tests/TestInputs.scala
  modules/directives/src/main/scala/scala/build/directives/HasBuildOptions.scala
  modules/directives/src/main/scala/scala/build/directives/HasBuildOptionsWithRequirements.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/CustomJar.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/Dependency.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/JavaOptions.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/JavaProps.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/JavacOptions.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/Resources.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/ScalacOptions.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/Toolkit.scala
  modules/generate-reference-doc/src/main/scala/scala/cli/doc/GenerateReferenceDoc.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  modules/options/src/main/scala/scala/build/options/BuildOptions.scala
  modules/options/src/main/scala/scala/build/options/BuildRequirements.scala
  website/docs/reference/directives.md
  website/docs/reference/scala-command/directives.md
Labels: enhancement

#2054 Fix invalid `scala-cli-signing` artifact downloads
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpExternalCommand.scala
  modules/integration/src/test/scala/scala/cli/integration/PgpTests.scala
  modules/options/src/main/scala/scala/build/internal/FetchExternalBinary.scala
  project/deps.sc
Labels: bug

#2065 NIT Remove dead `BuildDeps`
  project/deps.sc
  project/settings.sc
Labels: internal

#2064 Bump `jsoniter`, `scalameta`, `os-lib` and `scala-collection-compat`
  project/deps.sc
Labels: dependencies
