Repository VirtusLab/scala-cli, pull requests merged in 2023-03, with the labels that each got.

#1894 Tweak guides' and cookbooks' pages
  website/docs/commands/basics.md
  website/docs/commands/clean.md
  website/docs/commands/compile.md
  website/docs/commands/fmt.md
  website/docs/commands/package.md
  website/docs/commands/run.md
  website/docs/commands/shebang.md
  website/docs/commands/test.md
  website/docs/cookbooks/debugging.md
  website/docs/cookbooks/gh-action.md
  website/docs/cookbooks/gists.md
  website/docs/cookbooks/instant-startup-scala-scripts.md
  website/docs/cookbooks/intellij-multi-bsp.md
  website/docs/cookbooks/intellij-sbt-with-bsp.md
  website/docs/cookbooks/intellij.md
  website/docs/cookbooks/intro.md
  website/docs/cookbooks/native-images.md
  website/docs/cookbooks/scala-docker.md
  website/docs/cookbooks/scala-jvm.md
  website/docs/cookbooks/scala-package.md
  website/docs/cookbooks/scala-scripts.md
  website/docs/cookbooks/scala-versions.md
  website/docs/cookbooks/test-only.md
  website/docs/cookbooks/vscode.md
  website/docs/getting_started.md
  website/docs/guides/configuration.md
  website/docs/guides/dependencies.md
  website/docs/guides/ide.md
  website/docs/guides/internals.md
  website/docs/guides/intro.md
  website/docs/guides/piping.md
  website/docs/guides/proxies.md
  website/docs/guides/sbt-mill.md
  website/docs/guides/scala-js.md
  website/docs/guides/scala-native.md
  website/docs/guides/scripts.md
  website/docs/guides/shebang.md
  website/docs/guides/snippets.md
  website/docs/guides/update-dependencies.md
  website/docs/guides/using-directives.md
  website/docs/overview.md
  website/docs/under-the-hood.md
Labels: documentation

#1900 Add a guide for migrating from the old `scala` runner to Scala CLI
  website/docs/guides/intro.md
  website/docs/guides/old-runner-migration.md
  website/docs/reference/scala-command/index.md
Labels: documentation, SIP

#1910 Add a reference for available config keys in help & docs
  modules/cli/src/main/scala/scala/cli/commands/config/ConfigOptions.scala
  modules/config/src/main/scala/scala/cli/config/Key.scala
  modules/config/src/main/scala/scala/cli/config/Keys.scala
  modules/generate-reference-doc/src/main/scala/scala/cli/doc/ReferenceDocUtils.scala
  website/docs/commands/config.md
  website/docs/commands/publishing/publish-setup.md
  website/docs/reference/commands.md
  website/docs/reference/scala-command/commands.md
  website/docs/reference/scala-command/runner-specification.md
Labels: documentation, help

#1915 Fix handling for `experimental` features
  modules/build/src/main/scala/scala/build/preprocessing/DirectivesProcessor.scala
  modules/cli/src/main/scala/scala/cli/commands/RestrictableCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/RestrictedCommandsParser.scala
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/export0/Export.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretCreate.scala
  modules/cli/src/main/scala/scala/cli/commands/github/SecretList.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpPull.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpPush.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/Publish.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishLocal.scala
  modules/cli/src/main/scala/scala/cli/commands/publish/PublishSetup.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/HelpMessages.scala
  modules/cli/src/main/scala/scala/cli/util/ArgHelpers.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/Publish.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/PublishContextual.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/RequirePlatform.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/RequireScalaVersion.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/RequireScalaVersionBounds.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/RequireScope.scala
  modules/generate-reference-doc/src/main/scala/scala/cli/doc/GenerateReferenceDoc.scala
  modules/integration/src/test/scala/scala/cli/integration/RunScalaPyTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/SipScalaTests.scala
Labels: SIP

#1948 Temporarily disable `PublishTests.secret keys in config` on Windows
  modules/integration/src/test/scala/scala/cli/integration/PublishTestDefinitions.scala
Labels: internal

#1970 chore(dep): bump mill from 0.10.10 to 0.10.12
  .mill-version
Labels: dependencies

#1985 Print a better error when workspace path contains the `File.pathSeparator`
  modules/build/src/main/scala/scala/build/input/Inputs.scala
  modules/build/src/main/scala/scala/build/input/ScalaCliInvokeData.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
Labels: bug
