Repository VirtusLab/scala-cli, pull requests merged in 2023-05, with the labels that each got.

#2067 Remove the `examples` directory to fix `scala-steward` runs
  .github/workflows/ci.yml
  .gitignore
  examples/.gitignore
  examples/cross-build/.opts
  examples/cross-build/Hello.js.scala
  examples/cross-build/Hello.native.scala
  examples/java-print-class-path/Hello.java
  examples/java/Hello.java
  examples/jmh/.opts
  examples/jmh/Benchmarks.scala
  examples/junit/.opts
  examples/junit/MyTests.scala
  examples/scala-3/.opts
  examples/scala-3/foo3.sc
  examples/scala-files/simple.scala
  examples/scala-js/.opts
  examples/scala-js/foojs.sc
  examples/scala-jvm/Main.scala
  examples/scala-jvm/README.md
  examples/scala-native/.opts
  examples/scala-native/test.sc
  examples/scalatest/.opts
  examples/scalatest/Tests.scala
  examples/scripts/.opts
  examples/scripts/bar.sc
  examples/scripts/foo.sc
  examples/stacktraces-script/.opts
  examples/stacktraces-script/stack-traces.sc
  examples/stacktraces/.opts
  examples/stacktraces/StackTraces.scala
  examples/tests/.opts
  examples/tests/MyTests.scala
  examples/utest/.opts
  examples/utest/MyTests.scala
  modules/docs-tests/src/test/scala/sclicheck/ExampleTests.scala
Labels: bug

#2066 Refactor `using` directives processing
  modules/build/src/main/scala/scala/build/preprocessing/DataPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/DirectivesPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/DirectivesProcessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ExtractedDirectives.scala
  modules/build/src/main/scala/scala/build/preprocessing/JavaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/MarkdownCodeBlockProcessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/PreprocessingUtil.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/directives/DirectivesPreprocessingUtils.scala
  modules/build/src/main/scala/scala/build/preprocessing/directives/PartiallyProcessedDirectives.scala
  modules/build/src/main/scala/scala/build/preprocessing/directives/PreprocessedDirectives.scala
  modules/build/src/test/scala/scala/build/tests/DirectiveParsingTest.scala
  modules/directives/src/main/scala/scala/build/directives/ScopedDirective.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/ScopedDirective.scala
  modules/generate-reference-doc/src/main/scala/scala/cli/doc/GenerateReferenceDoc.scala
Labels: internal

#2072 Allow BSP to start successfully even with unrecognised `using` directives
  modules/build/src/main/scala/scala/build/preprocessing/DataPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/DirectivesPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/JavaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/MarkdownPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/directives/PreprocessedDirectives.scala
  modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
Labels: bug, IDE

#2073 Pass `invokeData` all the way to pre-processing to give more meaningful error/warning messages
  modules/build/src/main/scala/scala/build/Build.scala
  modules/build/src/main/scala/scala/build/CrossSources.scala
  modules/build/src/main/scala/scala/build/bsp/Bsp.scala
  modules/build/src/main/scala/scala/build/bsp/BspImpl.scala
  modules/build/src/main/scala/scala/build/input/ScalaCliInvokeData.scala
  modules/build/src/main/scala/scala/build/internal/util/WarningMessages.scala
  modules/build/src/main/scala/scala/build/preprocessing/DataPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/DirectivesPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/JarPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/JavaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/MarkdownPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/Preprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScalaPreprocessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScriptPreprocessor.scala
  modules/build/src/test/scala/scala/build/tests/PreprocessingTests.scala
  modules/build/src/test/scala/scala/build/tests/ScalaPreprocessorTests.scala
  modules/build/src/test/scala/scala/build/tests/SourcesTests.scala
  modules/build/src/test/scala/scala/build/tests/TestInputs.scala
  modules/cli/src/main/scala/scala/cli/commands/RestrictableCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/RestrictedCommandsParser.scala
  modules/cli/src/main/scala/scala/cli/commands/ScalaCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/config/Config.scala
  modules/cli/src/main/scala/scala/cli/commands/pgp/PgpCommand.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/HelpMessages.scala
  modules/cli/src/main/scala/scala/cli/util/ArgHelpers.scala
Labels: bug

#2082 Fix `ExcludeTests`
  modules/build/src/test/scala/scala/build/tests/ExcludeTests.scala
Labels: bug, internal

#2077 Bump `coursier` to `2.1.3`
  build.sc
  project/deps.sc
Labels: dependencies

#2078 Bump `graalvm` to `22.3.2`
  project/deps.sc
  website/docs/reference/cli-options.md
Labels: dependencies

#2099 Downgrade GraalVM to `22.3.1` to fix M1
  project/deps.sc
  website/docs/reference/cli-options.md
Labels: bug, dependencies

#2098 Fix `export` failing on input duplicates
  modules/build/src/main/scala/scala/build/CollectionOps.scala
  modules/build/src/main/scala/scala/build/CrossSources.scala
  modules/build/src/main/scala/scala/build/preprocessing/PreprocessedSource.scala
  modules/build/src/test/scala/scala/build/tests/DistinctByTests.scala
  modules/build/src/test/scala/scala/build/tests/SourcesTests.scala
  modules/cli/src/main/scala/scala/cli/commands/export0/Export.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportCommonTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/ExportTestProjects.scala
Labels: bug

#2101 Fix line conversion logic by simplifying topWrapperLen to line count of top wrapper
  modules/build/src/main/scala/scala/build/Build.scala
  modules/build/src/main/scala/scala/build/ConsoleBloopBuildClient.scala
  modules/build/src/main/scala/scala/build/GeneratedSource.scala
  modules/build/src/main/scala/scala/build/Sources.scala
  modules/build/src/main/scala/scala/build/bsp/BspClient.scala
  modules/build/src/main/scala/scala/build/bsp/BspServer.scala
  modules/build/src/main/scala/scala/build/postprocessing/LineConversion.scala
  modules/build/src/main/scala/scala/build/postprocessing/SemanticDbPostProcessor.scala
  modules/build/src/main/scala/scala/build/preprocessing/ScriptPreprocessor.scala
  modules/core/src/main/scala/scala/build/internals/CodeWrapper.scala
  modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/RunScriptTestDefinitions.scala
Labels: bug

#2114 Add developer docs on modifying `reflect-config.json`
  DEV.md
Labels: documentation, internal, DX

#2120 Fix the `--source-jar` option & add corresponding `using` directives
  modules/build/src/main/scala/scala/build/bsp/BspImpl.scala
  modules/build/src/main/scala/scala/build/bsp/BspServer.scala
  modules/build/src/test/scala/scala/build/tests/DirectiveTests.scala
  modules/cli/src/main/scala/scala/cli/commands/default/Default.scala
  modules/cli/src/main/scala/scala/cli/commands/package0/PackageOptions.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/SharedOptions.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/ClasspathUtils.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/CustomJar.scala
  modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
  website/docs/guides/dependencies.md
  website/docs/reference/cli-options.md
  website/docs/reference/directives.md
  website/docs/reference/scala-command/directives.md
Labels: bug, enhancement

#2127 Bump toolkit to `v0.1.7` and handle the separate `toolkit-test` dependency
  build.sc
  modules/build/src/test/scala/scala/build/tests/DirectiveTests.scala
  modules/build/src/test/scala/scala/build/tests/TestInputs.scala
  modules/cli/src/main/scala/scala/cli/commands/shared/SharedOptions.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/CustomJar.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/Dependency.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/JavaOptions.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/JavaProps.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/JavacOptions.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/Resources.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/ScalacOptions.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/Toolkit.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/TestTestDefinitions.scala
  modules/options/src/main/scala/scala/build/options/BuildOptions.scala
  modules/options/src/main/scala/scala/build/options/Scope.scala
  modules/options/src/main/scala/scala/build/options/WithBuildRequirements.scala
  project/deps.sc
Labels: enhancement, dependencies

#2137 Add a guide doc for toolkits & enforce all toolkits to have a separate `toolkit-test`
  build.sc
  modules/build/src/test/scala/scala/build/tests/DirectiveTests.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/Toolkit.scala
  modules/integration/src/test/scala/scala/cli/integration/RunTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/TestTestDefinitions.scala
  website/docs/guides/intro.md
  website/docs/guides/toolkit.md
  website/docs/guides/using-directives.md
Labels: documentation, enhancement

#2133 Improve directive parsing errors & special-case `toolkit` directive version parsing
  modules/build/src/test/scala/scala/build/tests/DirectiveTests.scala
  modules/directives/src/main/scala/scala/build/directives/DirectiveValueParser.scala
  modules/directives/src/main/scala/scala/build/errors/UsingDirectiveExpectationError.scala
  modules/directives/src/main/scala/scala/build/preprocessing/directives/DirectiveHandler.scala
  modules/integration/src/test/scala/scala/cli/integration/BspTestDefinitions.scala
Labels: UX

#2154 Fix publishing with implicit `publish.version` coming from a `git` tag
  modules/cli/src/main/resources/META-INF/native-image/org.virtuslab/scala-cli-core/reflect-config.json
  modules/integration/src/test/scala/scala/cli/integration/PublishLocalTestDefinitions.scala
  modules/integration/src/test/scala/scala/cli/integration/PublishLocalTests212.scala
  modules/integration/src/test/scala/scala/cli/integration/PublishLocalTests213.scala
  modules/integration/src/test/scala/scala/cli/integration/PublishLocalTestsDefault.scala
  modules/integration/src/test/scala/scala/cli/integration/PublishTestsDefault.scala
  modules/integration/src/test/scala/scala/cli/integration/TestUtil.scala
Labels: bug

#2173 Bump `scala-cli-signing` to `0.2.2`
  project/deps.sc
Labels: dependencies
